---
haproxy_host_config_listen:
  stats:
    bind: "*:8404"
    stats:
      - enable
      - uri /monitor
      - refresh 5s
    http-request: "deny if { src -f {{ haproxy_acl_directory }}/blocklist }"

haproxy_host_config_resolvers:
  dns:
    nameserver: "dns1 192.168.50.30:53"
    accepted_payload_size: 8192

haproxy_host_systemd_overrides:
  Service:
    LimitNOFILE: 500001

haproxy_acls_list_merge: append
haproxy_host_acls:
  blocklist:
    - 127.0.0.1/8
  test:
    content:
      - 10.0.0.0/8
      - 192.168.0.0/16
    backup: true
